"""
send_email.py
Sends the daily Excel report to Balu's Gmail via SMTP.
Requires env vars:
  GMAIL_SENDER        — the Gmail address you send FROM
  GMAIL_APP_PASSWORD  — Gmail App Password (not your real password)
  RECIPIENT_EMAIL     — where to deliver the report
"""

import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email              import encoders
from pathlib              import Path


def send_report(excel_path: str, job_summary: list[dict]) -> None:
    sender    = os.environ["GMAIL_SENDER"]
    password  = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ["RECIPIENT_EMAIL"]

    today_str = date.today().strftime("%B %d, %Y")

    # ── Build top-5 HTML list for email body ──────────────────────────────────
    top5 = [j for j in job_summary if j.get("stars", 0) >= 4][:5]
    apply_now_count = sum(1 for j in job_summary if j.get("apply_priority") == "APPLY NOW")
    fresher_count   = sum(1 for j in job_summary if j.get("is_fresher_friendly"))

    rows_html = ""
    for i, j in enumerate(top5, 1):
        rows_html += f"""
        <tr style="background:{'#f0fff4' if i%2==0 else '#ffffff'}">
          <td style="padding:8px;border:1px solid #ddd">{i}</td>
          <td style="padding:8px;border:1px solid #ddd"><b>{j.get('title','')}</b></td>
          <td style="padding:8px;border:1px solid #ddd">{j.get('company','')}</td>
          <td style="padding:8px;border:1px solid #ddd">{j.get('location','')}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center">{j.get('star_label','')}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center">
            <span style="color:{'#1a7a1a' if j.get('apply_priority')=='APPLY NOW' else '#b35900'};font-weight:bold">
              {j.get('apply_priority','')}
            </span>
          </td>
          <td style="padding:8px;border:1px solid #ddd">
            <a href="{j.get('link','#')}" style="color:#0563C1">View Job</a>
          </td>
        </tr>"""

    html_body = f"""
    <html><body style="font-family:Arial,sans-serif;color:#222;max-width:800px;margin:auto">

      <div style="background:#1F3864;color:#fff;padding:20px;border-radius:8px 8px 0 0">
        <h2 style="margin:0">🎯 Daily Java Job Report</h2>
        <p style="margin:4px 0;font-size:14px">{today_str} · Auto-generated by Claude AI + Apify</p>
      </div>

      <div style="background:#f8f9fa;padding:16px;border:1px solid #dee2e6">
        <b>Hi Balu 👋</b><br><br>
        Here's your daily Java fresher job report. Claude analyzed every job description
        against your resume and ranked them for you.
        <br><br>
        <table style="border-collapse:collapse;width:100%;margin-top:8px">
          <tr>
            <td style="background:#E2EFDA;padding:12px;border-radius:6px;text-align:center;width:33%">
              <div style="font-size:24px;font-weight:bold;color:#375623">{len(job_summary)}</div>
              <div style="font-size:12px;color:#555">Jobs Analyzed</div>
            </td>
            <td style="width:2%"></td>
            <td style="background:#DDEBF7;padding:12px;border-radius:6px;text-align:center;width:33%">
              <div style="font-size:24px;font-weight:bold;color:#1F3864">{fresher_count}</div>
              <div style="font-size:12px;color:#555">Fresher-Friendly</div>
            </td>
            <td style="width:2%"></td>
            <td style="background:#FCE4D6;padding:12px;border-radius:6px;text-align:center;width:30%">
              <div style="font-size:24px;font-weight:bold;color:#C00000">{apply_now_count}</div>
              <div style="font-size:12px;color:#555">Apply NOW</div>
            </td>
          </tr>
        </table>
      </div>

      <h3 style="color:#1F3864;margin:20px 0 8px">🏆 Top 5 Matches Today</h3>
      <table style="border-collapse:collapse;width:100%;font-size:13px">
        <tr style="background:#1F3864;color:#fff">
          <th style="padding:8px;border:1px solid #ddd">#</th>
          <th style="padding:8px;border:1px solid #ddd">Role</th>
          <th style="padding:8px;border:1px solid #ddd">Company</th>
          <th style="padding:8px;border:1px solid #ddd">Location</th>
          <th style="padding:8px;border:1px solid #ddd">Match</th>
          <th style="padding:8px;border:1px solid #ddd">Priority</th>
          <th style="padding:8px;border:1px solid #ddd">Link</th>
        </tr>
        {rows_html}
      </table>

      <div style="background:#fff8e1;border-left:4px solid #f59e0b;padding:12px;margin:20px 0;border-radius:0 6px 6px 0">
        <b>📎 Full report attached</b> — The Excel file has 4 sheets:
        Top Matches · Fresher Only · Skills Gap Analysis · Action Plan
      </div>

      <div style="background:#f1f5f9;padding:12px;border-radius:6px;font-size:12px;color:#666;margin-top:16px">
        This email was sent automatically by your Java Job Scout bot.<br>
        It runs every day at 10:00 AM IST via GitHub Actions.<br>
        Jobs are freshly scraped (last 24 hours only) and analyzed by Claude AI.
      </div>

    </body></html>
    """

    # ── Assemble MIME message ─────────────────────────────────────────────────
    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"🎯 Daily Java Jobs — {today_str} | {apply_now_count} APPLY NOW · {fresher_count} Fresher Friendly"
    msg["From"]    = sender
    msg["To"]      = recipient

    msg.attach(MIMEText(html_body, "html"))

    # Attach Excel
    with open(excel_path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
    encoders.encode_base64(part)
    filename = Path(excel_path).name
    part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
    msg.attach(part)

    # ── Send via Gmail SMTP ───────────────────────────────────────────────────
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender, password)
        smtp.sendmail(sender, recipient, msg.as_string())

    print(f"[email] Report sent to {recipient} ✅")


if __name__ == "__main__":
    # Quick test (won't actually send without env vars)
    print("send_email.py loaded OK. Set env vars and call send_report() to test.")
